// <auto-generated />
using System;
using Academia.Infra.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academia.Infra.Data.EF.Migrations
{
    [DbContext(typeof(AcademiaDbContext))]
    [Migration("20250214230551_PopulaTabelas")]
    partial class PopulaTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Academia.Domain.AlunoModulo.Aluno", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Altura")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Peso")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProfessorResponsavelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("AlunoId");

                    b.HasIndex("ProfessorResponsavelId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Academia.Domain.ProfessorModulo.Professor", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Academia.Domain.AlunoModulo.Aluno", b =>
                {
                    b.HasOne("Academia.Domain.ProfessorModulo.Professor", "ProfessorResponsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessorResponsavel");
                });

            modelBuilder.Entity("Academia.Domain.ProfessorModulo.Professor", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
